micronaut:
  application:
    name: java-micronaut-vertical
  server:
    context-path: /api
  serde:
    serialization:
      inclusion: NON_NULL
  security:
    reject-not-found: false
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver

jpa:
  default:
    entity-scan:
      packages: com.sakrafux.realworld
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false

endpoints:
  health:
    details-visible: ANONYMOUS