/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as EditorRouteImport } from "./routes/editor"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ProfileUsernameRouteImport } from "./routes/profile.$username"
import { Route as EditorSlugRouteImport } from "./routes/editor.$slug"
import { Route as ArticleSlugRouteImport } from "./routes/article.$slug"

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: "/editor",
  path: "/editor",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: "/profile/$username",
  path: "/profile/$username",
  getParentRoute: () => rootRouteImport,
} as any)
const EditorSlugRoute = EditorSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => EditorRoute,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: "/article/$slug",
  path: "/article/$slug",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/editor": typeof EditorRouteWithChildren
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/settings": typeof SettingsRoute
  "/article/$slug": typeof ArticleSlugRoute
  "/editor/$slug": typeof EditorSlugRoute
  "/profile/$username": typeof ProfileUsernameRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/editor": typeof EditorRouteWithChildren
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/settings": typeof SettingsRoute
  "/article/$slug": typeof ArticleSlugRoute
  "/editor/$slug": typeof EditorSlugRoute
  "/profile/$username": typeof ProfileUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/editor": typeof EditorRouteWithChildren
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/settings": typeof SettingsRoute
  "/article/$slug": typeof ArticleSlugRoute
  "/editor/$slug": typeof EditorSlugRoute
  "/profile/$username": typeof ProfileUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/editor"
    | "/login"
    | "/register"
    | "/settings"
    | "/article/$slug"
    | "/editor/$slug"
    | "/profile/$username"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/editor"
    | "/login"
    | "/register"
    | "/settings"
    | "/article/$slug"
    | "/editor/$slug"
    | "/profile/$username"
  id:
    | "__root__"
    | "/"
    | "/editor"
    | "/login"
    | "/register"
    | "/settings"
    | "/article/$slug"
    | "/editor/$slug"
    | "/profile/$username"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/editor": {
      id: "/editor"
      path: "/editor"
      fullPath: "/editor"
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profile/$username": {
      id: "/profile/$username"
      path: "/profile/$username"
      fullPath: "/profile/$username"
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/editor/$slug": {
      id: "/editor/$slug"
      path: "/$slug"
      fullPath: "/editor/$slug"
      preLoaderRoute: typeof EditorSlugRouteImport
      parentRoute: typeof EditorRoute
    }
    "/article/$slug": {
      id: "/article/$slug"
      path: "/article/$slug"
      fullPath: "/article/$slug"
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EditorRouteChildren {
  EditorSlugRoute: typeof EditorSlugRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorSlugRoute: EditorSlugRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
