server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:h2:file:@project.basedir@/realworld;DB_CLOSE_DELAY=-1"
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    default-property-inclusion: NON_NULL

realworld:
  auth:
    header: Authorization
    prefix: "Token "
    secret: ${JWT_SECRET:feNiAMDB8g1bMy7AvcKdYAEi++SpBdkrgM0ug6NPII4=}
    token-expiration-msec: 3600000 # 1 hour
  pagination:
    default-limit: 20
  cors:
    # Default to localhost for dev, but allow overriding via environment variable
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}

logging:
  level:
    root: INFO
    com.sakrafux.realworld: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
  file:
    name: "@project.basedir@/realworld.log"
  structured:
    format:
      file: ecs # The JSON format applies *only* to the file
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}){faint} %clr(%5p) %clr([%X{traceId:-}]){yellow} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"